spring:
  datasource:
    url: jdbc:mysql://47.99.53.71:3306/?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: hlj172532
    driver-class-name: com.mysql.cj.jdbc.Driver
