spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://47.99.53.71:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: hlj172532
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx_service_group: order_tx_group

# account 8081
# storage 8082
# order   8083
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #注册ip地址，而不是主机名

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.tedu.account.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn:
      tedu:
        account:
          mapper: debug
