package com.pd.mapper;

import com.pd.pojo.PdCartItem;
import com.pd.pojo.PdCartItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdCartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdCartItem> selectByExample(PdCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdCartItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdCartItem record, @Param("example") PdCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdCartItem record, @Param("example") PdCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_cart_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdCartItem record);
}