package com.pd.mapper;

import com.pd.pojo.PdCollectItem;
import com.pd.pojo.PdCollectItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdCollectItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdCollectItem> selectByExample(PdCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdCollectItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdCollectItem record, @Param("example") PdCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdCollectItem record, @Param("example") PdCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_collect_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdCollectItem record);
}