package com.pd.mapper;

import com.pd.pojo.PdItem;
import com.pd.pojo.PdItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdItem> selectByExample(PdItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdItem record, @Param("example") PdItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdItem record, @Param("example") PdItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdItem record);
}