package com.pd.mapper;

import com.pd.pojo.PdItemParam;
import com.pd.pojo.PdItemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdItemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdItemParam> selectByExampleWithBLOBs(PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdItemParam> selectByExample(PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdItemParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdItemParam record, @Param("example") PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PdItemParam record, @Param("example") PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdItemParam record, @Param("example") PdItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PdItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_param
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdItemParam record);
}