package com.pd.mapper;

import com.pd.pojo.PdUser;
import com.pd.pojo.PdUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdUser> selectByExample(PdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdUser record, @Param("example") PdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdUser record, @Param("example") PdUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_user
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdUser record);
}