# 在注册中心注册的服务名(服务id)
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 47.99.53.71
    port: 5672
    username: 47hlj
    password: hlj172532
# item  8001
# user  8101
# order 8201
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
