spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 47.99.53.71
    port: 5672
    username: 47hlj
    password: hlj172532
  zipkin:
    sender:
      type: rabbit
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
