spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 47.99.53.71
    port: 5672
    username: 47hlj
    password: hlj172532
server:
  port: 8101


# 自定义的配置属性
# 测试用的用户数据：[{id:7,username:xx,password:xx},{8},{9}]
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},
             {\"id\":8, \"username\":\"def\",\"password\":\"456\"},
             {\"id\":99, \"username\":\"hlj\",\"password\":\"hlj\"},
             {\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
