spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://47.99.53.71:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: hlj172532
    driver-class-name: com.mysql.cj.jdbc.Driver

# account 8081
# storage 8082
# order   8083
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #注册ip地址，而不是主机名

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.tedu.order.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn:
      tedu:
        order:
          mapper: debug
rocketmq:
  name-server: 47.99.53.71:9876
