package com.pd.mapper;

import com.pd.pojo.PdContentCategory;
import com.pd.pojo.PdContentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdContentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdContentCategory> selectByExample(PdContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdContentCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdContentCategory record, @Param("example") PdContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdContentCategory record, @Param("example") PdContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_content_category
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdContentCategory record);
}