package com.pd.mapper;

import com.pd.pojo.PdItemCat;
import com.pd.pojo.PdItemCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdItemCat> selectByExample(PdItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdItemCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdItemCat record, @Param("example") PdItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdItemCat record, @Param("example") PdItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_item_cat
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdItemCat record);
}