package com.pd.mapper;

import com.pd.pojo.PdOrder;
import com.pd.pojo.PdOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdOrder> selectByExample(PdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdOrder record, @Param("example") PdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdOrder record, @Param("example") PdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdOrder record);
}