package com.pd.mapper;

import com.pd.pojo.PdOrderItem;
import com.pd.pojo.PdOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdOrderItem> selectByExample(PdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdOrderItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdOrderItem record, @Param("example") PdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdOrderItem record, @Param("example") PdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_order_item
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdOrderItem record);
}