package com.pd.mapper;

import com.pd.pojo.PdShipping;
import com.pd.pojo.PdShippingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    long countByExample(PdShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByExample(PdShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int deleteByPrimaryKey(Long addId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insert(PdShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int insertSelective(PdShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    List<PdShipping> selectByExample(PdShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    PdShipping selectByPrimaryKey(Long addId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") PdShipping record, @Param("example") PdShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByExample(@Param("record") PdShipping record, @Param("example") PdShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(PdShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pd_shipping
     *
     * @mbg.generated Thu Oct 11 11:44:42 CST 2018
     */
    int updateByPrimaryKey(PdShipping record);
}