# 在注册中心注册的服务名(服务id)
spring:
  application:
    name: item-service

# item  8001
# user  8101
# order 8201
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
